version: "3.8"

services:
  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    container_name: blog_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./blog/.env
    networks:
      - blog_network

  mysql:
    image: mysql:8.0.33
    container_name: mysql_container
    restart: always
    env_file:
      - ./blog/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - blog_network

volumes:
  mysql_data:

networks:
  blog_network:
